javascript runner can be specified when package.json has multiple runners
vim-test/vim-test pull request #514
Opened 2020-08-27 09:55 UTC by vfbiby

#### JavaScript

Test runner detection for JavaScript works by checking which runner is listed in the package.json dependencies. If you have globally installed the runner make sure it's also listed in the dependencies. And now you can specify a runner when hava multiple runners listed in package.json dependencies. 
```vim
let g:test#javascript#runner = 'jest'
```

and fix a warning

not ok 16 - Maven Junit3 multimodule tests runs a test suite with user provided options
 {example}，第 4 行
 Vim(call):E488: Trailing characters:
spec/maventest_spec.vim .......... Failed 1/28 subtests

Make sure these boxes are checked before submitting your pull request:

- [x] Add fixtures and spec when implementing or updating a test runner
- [x] Update the README accordingly
- [ ] Update the Vim documentation in `doc/test.txt`

2020-08-31 15:24 UTC, codeinabox requested changes
LGTM just remove the commented out code and I am happy to merge

2020-08-31 15:24 UTC, codeinabox commented on autoload/test/javascript/cucumberjs.vim
> +  "endif
Please remove this commented out code

2020-08-31 15:24 UTC, codeinabox commented on autoload/test/javascript/webdriverio.vim
> +    "\ && !empty(glob('wdio.conf.js'))
Please remove commented out code

2020-09-01 12:56 UTC, vfbiby commented on autoload/test/javascript/webdriverio.vim
> +    "\ && !empty(glob('wdio.conf.js'))
sure!

2020-09-01 13:59 UTC, codeinabox approved these changes

2020-09-01 14:00 UTC, merged