Fixes Issues with Vitest Implementation
vim-test/vim-test pull request #699
Opened 2022-10-31 02:06 UTC by harrisoncramer

Not super good with Vimscript but this seems to fix the TestNearest funcitonality for me for Vitest, relates to https://github.com/vim-test/vim-test/issues/698

2022-10-31 02:09 UTC, harrisoncramer commented on spec/vitest_spec.vim
> +    it "runs JSX"
Vitest supports Javsacript out of the box and the default configuration should also support JS. The previous author had mislabeled JSX extensions as "Javascript" and TSX extensions as "React" which is a bit odd

2022-11-01 10:03 UTC, maorun commented
if we removes $ or ^ other tests will also run.
perhaps something is missing to use `-t` (testNamePattern)

```
describe('dont will', () => {
    it('should do good stuff', () => {
        console.log('a')
        expect(true).toBeTruthy()
    })
})

describe('will', () => {
    it('should do good stuff', () => {
        expect(true).toBeTruthy()
    })
    it('should do good stuff and other things', () => {
        expect(true).toBeTruthy()
    })
    it('should do good stuff but only on something', () => {
        expect(true).toBeTruthy()
    })
})
```

2022-11-10 13:16 UTC, codeinabox commented
Would you like a hand fixing these failing tests?

2022-11-11 12:32 UTC, v-ostark commented
Any update on this?

2022-11-11 12:53 UTC, harrisoncramer commented
Hey @codeinabox yes, a hand fixing the failing tests would be great!

2022-11-13 20:13 UTC, codeinabox commented
> Hey @codeinabox yes, a hand fixing the failing tests would be great!

I'll have a look into this next week

2022-12-15 07:59 UTC, v-ostark commented
Can we merge this?

2022-12-15 10:31 UTC, codeinabox commented
> Can we merge this?

Once we have resolved the tests failing on CI

2022-12-15 10:37 UTC, codeinabox requested changes
The following test are failing:

### vitest runs file test if nearest test couldn't be found

Expected g:test#last_command == g:expectedExecutable .. 'vitest run --no-coverage __tests__/normal-test.jsx' at line 5

Actual value: "npx vitest run --no-coverage -t '' __tests__/normal-test.jsx"
Expected value: "npx vitest run --no-coverage __tests__/normal-test.jsx"

### vitest on nearest tests runs Javascript

Expected g:test#last_command == g:expectedExecutable .. 'vitest run --no-coverage -t ''Math'' __tests__/normal-test.js' at line 4

Actual value: "npx vitest run --no-coverage -t '' __tests__/normal-test.js"
Expected value: "npx vitest run --no-coverage -t 'Math' __tests__/normal-test.js"

2022-12-31 17:22 UTC, codeinabox commented
So I've managed to get the tests passing. Firstly I reverted the logic to only set `-t` when there is a name. I noticed the tests for normal-test.js you added were failing though it's not clear why, however removing them the tests are now passing. If there are no objects I am keen to get this merged in

2023-01-01 14:08 UTC, codeinabox approved these changes

2023-01-05 10:14 UTC, merged