fix:  wrong module name in maven multi-level projects #677
vim-test/vim-test pull request #739
Opened 2023-07-05 20:41 UTC by GiuseppeMP

Make sure these boxes are checked before submitting your pull request:

- [x] Add fixtures and spec when implementing or updating a test runner
- [] Update the README accordingly (no change needed)
- [] Update the Vim documentation in `doc/test.txt` (no change needed)

2023-07-06 20:46 UTC, codeinabox commented on autoload/test/java/maventest.vim
> +  " let l:module_name = fnamemodify(project_dir, ':t')
If this is no longer needed, could it please be removed

2023-07-06 20:48 UTC, codeinabox requested changes
Thank you for this, looking good! Could you please remove the comment and also the `.settings` directory in the fixtures

2023-07-08 22:52 UTC, GiuseppeMP commented
@codeinabox Hey,

Comments resolved.

2023-07-10 17:41 UTC, codeinabox approved these changes
Thank you for this!

2023-07-10 17:42 UTC, merged